### ISSUE TITLE
For the dataset, I download fail in train data set,Could it please give other link likes baidu network disk?thanks

### ISSUE THREAD

**Issue by buwangchuxin1992** [sczhou/LEDNet#4]

**Comment by sczhou** [comment]
We didn't upload the data to BaiduPan since we notice it's very slow unless one upgrades to the VIP account.
Can you download the test set from Google Drive? If so, I can upload the training folders separately along with five small .zip files. 

---
Update:

5 zip files have been uploaded to google drive, you can find them in the `train_separate_zip` folder from
https://drive.google.com/drive/folders/11HcsiHNvM7JUlbuHIniREdQ2peDUhtwX?usp=sharing
Please try it again. 

We will also upload them to BaiduPan tonight.

**Comment by buwangchuxin1992** [comment]
thanks for your dataset
